// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./../src/components/overlay/AboutDialog.vue')['default']
    AboutModal: typeof import('./../src/components/modal/AboutModal.vue')['default']
    AppBar: typeof import('./../src/components/app/AppBar.vue')['default']
    AppModal: typeof import('./../src/components/app/AppModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
